export default {
  "value":[
     {
        "id":"/subscriptions/2ab38134-2945-48e0-bdc3-0e3bd0307bc0/resourceGroups/test/providers/Microsoft.Web/sites/test-logging-pdd",
        "name":"test-logging-pdd",
        "type":"Microsoft.Web/sites",
        "kind":"app",
        "location":"South Central US",
        "tags":{
           "hidden-related:/subscriptions/2ab38134-2945-48e0-bdc3-0e3bd0307bc0/resourcegroups/test/providers/Microsoft.Web/serverfarms/free":"empty"
        },
        "properties":{
           "name":"test-logging-pdd",
           "state":"Running",
           "hostNames":[
              "test-logging-pdd.azurewebsites.net"
           ],
           "webSpace":"test-SouthCentralUSwebspace",
           "selfLink":"https://waws-prod-sn1-151.api.azurewebsites.windows.net:454/subscriptions/2ab38134-2945-48e0-bdc3-0e3bd0307bc0/webspaces/test-SouthCentralUSwebspace/sites/test-logging-pdd",
           "repositorySiteName":"test-logging-pdd",
           "owner":null,
           "usageState":"Normal",
           "enabled":true,
           "adminEnabled":true,
           "enabledHostNames":[
              "test-logging-pdd.azurewebsites.net",
              "test-logging-pdd.scm.azurewebsites.net"
           ],
           "siteProperties":{
              "metadata":null,
              "properties":[

              ],
              "appSettings":null
           },
           "availabilityState":"Normal",
           "sslCertificates":null,
           "csrs":[

           ],
           "cers":null,
           "siteMode":null,
           "hostNameSslStates":[
              {
                 "name":"test-logging-pdd.azurewebsites.net",
                 "sslState":"Disabled",
                 "ipBasedSslResult":null,
                 "virtualIP":null,
                 "thumbprint":null,
                 "toUpdate":null,
                 "toUpdateIpBasedSsl":null,
                 "ipBasedSslState":"NotConfigured",
                 "hostType":"Standard"
              },
              {
                 "name":"test-logging-pdd.scm.azurewebsites.net",
                 "sslState":"Disabled",
                 "ipBasedSslResult":null,
                 "virtualIP":null,
                 "thumbprint":null,
                 "toUpdate":null,
                 "toUpdateIpBasedSsl":null,
                 "ipBasedSslState":"NotConfigured",
                 "hostType":"Repository"
              }
           ],
           "computeMode":null,
           "serverFarm":null,
           "serverFarmId":"/subscriptions/2ab38134-2945-48e0-bdc3-0e3bd0307bc0/resourceGroups/test/providers/Microsoft.Web/serverfarms/free",
           "reserved":false,
           "lastModifiedTimeUtc":"2017-10-25T22:39:22.8366667",
           "storageRecoveryDefaultState":"Running",
           "contentAvailabilityState":"Normal",
           "runtimeAvailabilityState":"Normal",
           "siteConfig":null,
           "deploymentId":"test-logging-pdd",
           "trafficManagerHostNames":null,
           "sku":"Free",
           "scmSiteAlsoStopped":false,
           "targetSwapSlot":null,
           "hostingEnvironment":null,
           "hostingEnvironmentProfile":null,
           "clientAffinityEnabled":true,
           "clientCertEnabled":false,
           "hostNamesDisabled":false,
           "domainVerificationIdentifiers":null,
           "kind":"app",
           "outboundIpAddresses":"13.66.38.99,13.66.35.170,13.66.36.236,13.66.32.249,52.171.63.58",
           "possibleOutboundIpAddresses":"13.66.38.99,13.66.35.170,13.66.36.236,13.66.32.249,52.171.63.58,13.66.38.99",
           "containerSize":0,
           "dailyMemoryTimeQuota":0,
           "suspendedTill":null,
           "siteDisabledReason":0,
           "functionExecutionUnitsCache":null,
           "maxNumberOfWorkers":null,
           "homeStamp":"waws-prod-sn1-151",
           "cloningInfo":null,
           "snapshotInfo":null,
           "hostingEnvironmentId":null,
           "tags":{
              "hidden-related:/subscriptions/2ab38134-2945-48e0-bdc3-0e3bd0307bc0/resourcegroups/test/providers/Microsoft.Web/serverfarms/free":"empty"
           },
           "resourceGroup":"test",
           "defaultHostName":"test-logging-pdd.azurewebsites.net",
           "slotSwapStatus":null
        }
     }
  ],
  "nextLink":null,
  "id":null
}
